# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'chitchatHybrid' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chitchatHybrid
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Database'



  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'chitchatHybridTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chitchatHybrid-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chitchatHybrid-tvOS


end
